### ISSUE TITLE
Release teal.code

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.code#100]
### Summary
The release strategy is now "on-demand" and with the qenv and refactor development wrapping up ([here](https://github.com/insightsengineering/NEST-roadmap/issues/45) and [here](https://github.com/insightsengineering/NEST-roadmap/issues/69)), we should plan for release for all affected packages on the next increment.

### Packages to be released:
* ~~teal~~
* teal.code
* ~~teal.widgets~~
* ~~teal.slice~~
* ~~tmg~~
* ~~tmc~~
* ~~teal.goshawk~~
* ~~teal.osprey~~
* ~~tmhermes~~
* ~~tmhelios~~

As discussed, we will do two stage releases:
1. release teal.code
2. release teal modules and rest of teals

We will perform release 1 in `2023.i1.s1` and discuss the timing for release 2 with the team.

### Tasks
* Check README files for affected packages
* For breaking changes, make sure to update the version in downstream packages. For more information, see the **VERSION UPDATE2** in this [comment](https://github.com/insightsengineering/NEST-roadmap-roche/issues/35#issuecomment-1257774355).

**Comment by donyunardi** [comment]
@insightsengineering/nest-core-dev 
Could you please help check if I got all the affected packages in the original comment?
Please edit if I miss anything.

**Comment by nikolas-burkoff** [comment]
so I strongly suspect you'll need to release lots of packages -> for example if you are releasing tmc then it now contains `tm_a_gee` which means we need a version of tern.gee available that works with main of tmc. Has tern/tern.mmrm changed at all to allow any other features of tmc to work?

tmc/tern may well require a release of rtables and formatters I suspect. All the teal packages are about to use new functionality from teal.transform so you'll need that. 

Has tmhelios been released before? Is it ready? I assume helios would need to be released as well as they are co-developed

In principle moving to on demand release makes sense - in practice so much stuff is so coupled together and we're still making large changes everywhere - I think in practice at least for the next few releases (until we get to teal 1.0) we're going to need to release most things.

Separately I wonder about how our user base/support model is going to work (thoughts on this @npaszty? @cicdguy ) Instead of having "release Oct 2022" we're going to have a set of packages released at different times so if users have problems they are going to have to say I'm using version x of teal but version y of teal.transform etc. This could make supporting users and directing them to appropriate (internal) documentation more challenging. I guess we could decouple the release of packages from their deployment in internal systems but that could confuse things even further...

Finally from a validation stand point - do we yet have confidence that if we release some parts of NEST we won't break other parts and also if people are using these packages to make critical business decisions then do they want "LTS versions" etc.

**Comment by asbates** [comment]
A lot of good points here @nikolas-burkoff. I think whatever the release cadence a good goal is to have the ability to release packages independently even if that's not actually how releases are done. It's pretty clear there's still a lot of dependencies across NEST (and outside e.g. rtables). This adds a lot of complexity and time, and increases the chance of problems. Because of these dependencies I don't think we're at the stage yet to be able to do independent releases. Perhaps in theory but like you said I think practically it's probably not a good idea.

I'm sure this has already been discussed but I think a lot of teams need to be involved to define the release cadence. All the different development teams, product owners, IDR, users, ... A lot of this will probably depend on internal systems. Can they all do a snapshot of packages? If so then maybe an LTS model could work. But what if there's bugs? Do the snapshots get updated, is there a new one created? There's so many possibilities it's going to take a number of people a long time to decide on what works for everyone. I really like the idea of an LTS, maybe at the entire teal/nest level vs. individual packages.

One of the hardest things about this is going to be balancing internal needs and expectations with community needs and expectations. As an outsider, I'd expect all packages to be pretty much independent so I don't have to worry about having version 0.1 of teal, 0.2.3 of teal.data, etc. That has been one of the most confusing things for me. With R more generally, sometimes I know I may need a development version of a package for example. But I don't think I've ever had to have very specific versions of many packages. I think it's a matter of what the intent of the nest ecosystem is. How much do we want it to be for internal use vs. community use?

I'm wondering if there's some sort of document showing the relationships between all the packages? Like maybe a graph. This would probably help with release decisions vs. having it all in someone's head.

**Comment by nikolas-burkoff** [comment]
🤯 - I'm not sure this is comprehensible/maintainable as is
![image](https://user-images.githubusercontent.com/15201933/207929961-3bcdc0d0-7cd8-4e04-b6d9-9428dec014ce.png)

(from `staged.dependencies::install_deps_app(default_repo = "insightsengineering/teal", default_ref = "main", run_gadget = FALSE)`)

**Comment by donyunardi** [comment]
I think the on-demand integration test plays a huge role in our on-demand release method since it will check if the package(s) can be released and not break anything. For the `tmc` and `tern.gee` scenarios, I expect the integration test will fail, which means we will need to release `tern.gee` as well.

Understandably, we may need to release most things in the next couple of releases since some aspects of our products are coupled together. I think that's okay for now and we will improve this. Also, if I recall, one of the goals for on-demand releases is to relieve the pressure that normally happened during the release sprint.

I see the point about user support. It is convenient to be able to refer to the "Oct Release", as opposed to specifying the version of each package when wanting to get some help to reproduce the environment. Maybe we can use renv lock file? Or RSPM snapshot feature?

Although I don't see much issue about documentation but maybe I'm missing something.

**Comment by donyunardi** [comment]
As discussed, we will do two stage releases:
1. release teal.code, teal.slice, teal.widgets
2. release teal and modules

We will release 1 in `2023.i1.s1` and discuss the timing for release 2 with the team.

**Comment by donyunardi** [comment]
teal.code 0.3.0 is now released.
Thanks Team!
