### ISSUE TITLE
[Feature Request]: Method to list names of the objects in `@env`.

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.code#175]
### Feature description

We need a method to get names from @env to not force users to get directly from the slot `ls(<qenv>@env)`. Ideally we would like to use `ls(<qenv>)` or `objects(<qenv>)` but these functions are not registered generics in base.
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
I propose a method `names()` if `ls()` and `objects()` is not possible. @chlebowa

**Comment by pawelru** [comment]
I personally see nothing wrong with `ls(x@env)` hence I suggest dropping this.

I see a bigger risk here. Once you do `ls` (or anything like that), sooner or later we would want to add `parent.env()`, `env_get()` (probably already exists), `env_set()`, `env_clone()`  and other methods / functions that accepts environment object. This won't stop. Therefore I would say we would recommend using `x@env` directly. It's easier, more flexible and cheaper (in terms of time).

**Comment by chlebowa** [comment]
@pawelru I disagree. We don't want to force deep `qenv` knowledge upon the users so a public method to list all contents of a `teal_data` object is not an unreasonable demand. The functions you listed (`parent.env()`, `env_get()`, `env_set()`, `env_clone()`) seem so far outside of the intended use of the `teal_data` class, a user who would actually want them would be able to implement them themselves.

> recommend using `x@env` directly

This runs against everything we have been doing so far. We export methods to interact with slots. It is generally discouraged to access slots directly. _Our vignettes_ discourage accessing slots directly.

**Comment by pawelru** [comment]
OK I got your point and you are right. Then how about `ls(x$get_env())`?
IMO exposing env slot (for further use) gives much more flexibility rather than just one method after which there will be yet another one and so on and so forth...

**Comment by chlebowa** [comment]
As for the name, the reason I don't like `ls` (regardless of not being a generic) is that it is used for environments and we do not advertise `qenv` as an environment but as a container that holds data and tracks code. (Side note: I would argue that the phrasing _Reproducible class with environment and code_ found in the documentation is not ideal but that will probably change with #166 .) I would actually like `objects` but that is a synonym to `ls`. I also don't like `names` because it generally returns the `names` attribute which holds names of elements of an object. `qenv` does not have elements as such unless one considers slots and that is not what we want. Furthermore, `names(<teal_data>)` and `datanames(<teal_data>)` could be confusing.

Sorry for not responding sooner but my mind was (is) occupied by rewriting vignettes.

I suggest `contents(<qenv>)`.

**Comment by chlebowa** [comment]
> OK I got your point and you are right. Then how about `ls(x$get_env())`? IMO exposing env slot (for further use) gives much more flexibility rather than just one method after which there will be yet another one and so on and so forth...

I thought we wanted to _limit_ flexibility in the name of reproducibility. So far we have (or are on track to):
* forbidden creating `qenv` with code
* added a verification feature to `teal_data`
* ... I feel I am forgetting something :thinking:

**Comment by pawelru** [comment]
> > OK I got your point and you are right. Then how about `ls(x$get_env())`? IMO exposing env slot (for further use) gives much more flexibility rather than just one method after which there will be yet another one and so on and so forth...
> 
> I thought we wanted to _limit_ flexibility in the name of reproducibility. So far we have (or are on track to):
> 
> * forbidden creating `qenv` with code
> * added a verification feature to `teal_data`
> * ... I feel I am forgetting something 🤔

Above are limits on _setter_ functionalities which are critical for reproducibility as you correctly pointed out. I believe that this is achieved by `lockEnvironment` (and possibly other). My point here is to expose (locked) environment for further _getter_ actions like `ls()` and possibly others. 

My concern here is that the list of _getter_ actions is pretty much unknown and big enough to state that we won't cover everything and choosing such a route is very expensive in terms of development and maintenance efforts.

**Comment by m7pr** [comment]
Hey, I see this discussion is still not resolved. Let me cheap in!

First of all we are about to make a method for `teal_data/qenv` object, not for `teal_data/qenv@env` so I don't think we will have issues with `parent.env(), env_get(), env_set(), env_clone()``ever being mentioned or needed.

I would strive from `names` being a name, as my intuition states that this should return slot names from `teal_data/qenv` and not objects stored in `teal_data/qenv@qenv`. For `contents` applied to `teal_data/qenv` I suppose this should return something similar to `str`, hence I'm the biggest fan and supporter of `objects`.

I don't think we should specifically create `x@get_env()` as this is more R6 like and would work if we have private fields. However if you start typing `x@` you enter a dangerous path where user can see what's included inside, and I think we strongly discourage such use. So it should rather be a method applied on an object `get_env(x)` instead of a function being binded with an object in a separate slot.

Probably my few words does not solve the conversation, but I would go with an S4 method called `objects()` being applied  directly on `qenv` .

**Comment by averissimo** [comment]
I would prefer to keep all slot-based operations contained within this package _(even if they are just simple wrappers)_ and avoid direct access of them elsewhere. The ideia of having to search for `@env` across all packages and deprecate it if for some reason this is refactored/changed comes to mind.

`ls` and `objects` would make the most sense, but they are not exposed as S3 methods in base R :disappointed: :shrug:  

However, there's a workaround if we are willing to define and export the `as.environment.qenv` method. There might be some negative repercussions of having this method though.

If workaround is not acceptable, then I think we should be pragmatic and create a new function name. `list.vars(<qenv>)` (in line with list.files), `ls.vars(<qenv>)` (should be sfe as there are other non-S3 `ls.*` functions), `get_vars(<qenv>)` (plural of a function we already have) or `get_var(<qenv>, <missing>)` _(sneaky way, my least favorite as it's implicit)_

``` r
library(teal.code)
q1 <- qenv() |>
  within({
    bb <- 2
    aa <- iris
  })

try(ls(q1))
#> Error in as.environment(pos) : 
#>   S4 object does not extend class "environment"

as.environment.qenv <- function(x) {
  x@env
}

ls(q1)
#> [1] "aa" "bb"
objects(q1)
#> [1] "aa" "bb"
```

<sup>Created on 2023-12-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by chlebowa** [comment]
> However, there's a workaround if we are willing to define and export the `as.environment.qenv` method. There might be some negative repercussions of having this method though.

You mean `as.environment` for converting a `qenv` to an `environment` and then doing `names(as.environment(<qenv>))`?

It's clean but a little cumbersome. If it's only for in-teal use, I like it.

**Comment by averissimo** [comment]
Actually there's no need for `names(as.environment(<qenv>))`. `ls(<qenv>)` just works.

**Comment by chlebowa** [comment]
> Actually there's no need for `names(as.environment(<qenv>))`. `ls(<qenv>)` just works.

Yup, that's what I meant :+1:

**Comment by pawelru** [comment]
At first I really liked this but this has some limitations - its working only when passed as an argument which then is converted to env with `as.environment()`. For now I identify that's true for `ls()` (which is the goal for this issue) and `assign()` (which usage is very much against the `qenv` concept). 
Because of that:
```
ls(q1)
#> [1] "aa" "bb"
ls(envir = q1)
#> Error in ls(envir = q1): invalid 'envir' argument
```

**Comment by gogonzo** [comment]
> q1 |> get_env() |> ls()

This is the nicest solution in my opinion.

**Comment by m7pr** [comment]
Hey, a short proposition for `get_env,qenv-method` can be found here https://github.com/insightsengineering/teal.code/pull/187
