### ISSUE TITLE
Document list of exceptions from joining qenv objects

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.code#71]
_Originally posted by @pawelru in https://github.com/insightsengineering/teal.code/pull/66#discussion_r972063980_

- make it publicly available (not a private fun docs)
- make it once only not to maintain multiple places

**Comment by donyunardi** [comment]
Be sure to include comments from @nikolas-burkoff 
https://github.com/insightsengineering/teal.code/issues/56#issuecomment-1219388007
https://github.com/insightsengineering/teal.code/issues/56#issuecomment-1220818098
https://github.com/insightsengineering/teal.code/issues/56#issuecomment-1220813989

The goal is to make user aware of the exceptions and how to handle them.

**Comment by donyunardi** [comment]
Reading through the PR #66, I believe the original request is to combine the roxygen documentation for `.check_joinable` function and `join` method into one area that is public. 

We also have pre-defined rules:
1. all private functions should have `@keywords internal`.
1. private functions shouldn't be exposed in the public docs (to avoid users using private functions).
1. internal functions not listed in pkgdown.

If we're keeping `.check_joinable` as internal, then how about refer the roxygen documentation for `.check_joinable` to the `join` method.

```
#' If two `qenv` can be joined
#'
#' Checks if two `qenv` objects can be combined.
#' For more information, please read `?join`
#'
#' @param x (`qenv`)
#' @param y (`qenv`)
#' @return `TRUE` if able to join or `character` used to print error message.
#' @keywords internal
.check_joinable <- function(x, y) {
```

Then under `join` method (public because it's exported), we explain everything.
@gogonzo what do you think?
